### ISSUE TITLE
How to start to integrate with goUmbral?

### ISSUE THREAD

**Issue by KimiWu123** [nucypher/goUmbral#21]
In pyUmbral, there are `generate_kfrags`, `reencrypt`, `decrypt` ... etc function to generate re-encryption key or re-encrypt files. However, I can't see any similar functions in this project. How could I start to use goUmbral? Or if I'd like to help/contribute, how to start? Thanks!

**Comment by cygnusv** [comment]
hi @KimiWu123!
The development of goUmbral has been slowed down as we focus most of our current efforts in the [nucypher project](https://github.com/nucypher/nucypher/). 
Right now, the underlying math layer in goUmbral is practically ready, so what it's left is to start implementing the PRE functionality. The place that I would start is to implement the [Umbral keys module](https://github.com/nucypher/pyUmbral/blob/master/umbral/keys.py). 

Feel free to open a PR!

**Comment by KimiWu123** [comment]
Hi @cygnusv 
I started to implement from curvebn which maps to [python curvebn](https://github.com/nucypher/pyUmbral/blob/master/umbral/curvebn.py). 

I downloaded [openssl 1.1.1](https://github.com/openssl/openssl/releases), but there is no `opensslconf.h` in the package (only `opensslconf.h.in` in the package). It causes build error. If I renamed `opensslconf.h.in` to `opensslconf.h`, it still have errors. Would you mind sharing your environment settings or openssl packages to me? 

Is it okay to discuss/ask issues/questions I met in this thread? Or other places I can ask?

Thanks. 

-------

I found `modbn` is `curvebn` of golang version... but build error still exists.

**Comment by tuxxy** [comment]
I'd prefer if we could take this discussion to our Discord, here's an invite: https://discord.gg/gGyUcwP

To answer your question, `ModBN` is the goUmbral version of the `CurveBN`. I also made a promise to @jMyles that I would change it eventually heh.
